In [1]:
import pandas as pd 
a=pd.read_csv(r"C:\Users\subhadip sinha\OneDrive\CODING\PYTHON\Scikit-Learn\not_CSV\adult.data")
a

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [2]:
a=pd.read_csv(r"C:\Users\subhadip sinha\OneDrive\CODING\PYTHON\Scikit-Learn\not_CSV\adult.data",header=None)
a

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [7]:
a.columns=["id","job","id_0","culafication","Roll","marrage_or_not","a","famely","color","gender","id_1","id_2","id_3","State","income"]

In [8]:
a

,id,job,id_0,culafication,Roll,marrage_or_not,a,famely,color,gender,id_1,id_2,id_3,State,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              32561 non-null  int64
 1   job             32561 non-null  object
 2   id_0            32561 non-null  int64
 3   culafication    32561 non-null  object
 4   Roll            32561 non-null  int64
 5   marrage_or_not  32561 non-null  object
 6   a               32561 non-null  object
 7   famely          32561 non-null  object
 8   color           32561 non-null  object
 9   gender          32561 non-null  object
 10  id_1            32561 non-null  int64
 11  id_2            32561 non-null  int64
 12  id_3            32561 non-null  int64
 13  State           32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [10]:
bb=pd.read_csv(r"C:\Users\subhadip sinha\OneDrive\CODING\PYTHON\Scikit-Learn\not_CSV\adult.test")
bb

                                                                                                                                             |1x3 Cross validator
25 Private      226802 11th         7  Never-married      Machine-op-inspct Own-child      Black              Male   0    0 40 United-States               <=50K.
38 Private      89814  HS-grad      9  Married-civ-spouse Farming-fishing   Husband        White              Male   0    0 50 United-States               <=50K.
28 Local-gov    336951 Assoc-acdm   12 Married-civ-spouse Protective-serv   Husband        White              Male   0    0 40 United-States                >50K.
44 Private      160323 Some-college 10 Married-civ-spouse Machine-op-inspct Husband        Black              Male   7688 0 40 United-States                >50K.
18 ?            103497 Some-college 10 Never-married      ?                 Own-child      White              Female 0    0 30 United-States               <=50K.
...                                                                                                                                                           ...
39 Private      215419 Bachelors    13 Divorced           Prof-specialty    Not-in-family  White              Female 0    0 36 United-States               <=50K.
64 ?            321403 HS-grad      9  Widowed            ?                 Other-relative Black              Male   0    0 40 United-States               <=50K.
38 Private      374983 Bachelors    13 Married-civ-spouse Prof-specialty    Husband        White              Male   0    0 50 United-States               <=50K.
44 Private      83891  Bachelors    13 Divorced           Adm-clerical      Own-child      Asian-Pac-Islander Male   5455 0 40 United-States               <=50K.
35 Self-emp-inc 182148 Bachelors    13 Married-civ-spouse Exec-managerial   Husband        White              Male   0    0 60 United-States                >50K.

[16281 rows x 1 columns]

In [12]:
bb=pd.read_csv(r"C:\Users\subhadip sinha\OneDrive\CODING\PYTHON\Scikit-Learn\not_CSV\adult.test")
bb

                                                                                                                                             |1x3 Cross validator
25 Private      226802 11th         7  Never-married      Machine-op-inspct Own-child      Black              Male   0    0 40 United-States               <=50K.
38 Private      89814  HS-grad      9  Married-civ-spouse Farming-fishing   Husband        White              Male   0    0 50 United-States               <=50K.
28 Local-gov    336951 Assoc-acdm   12 Married-civ-spouse Protective-serv   Husband        White              Male   0    0 40 United-States                >50K.
44 Private      160323 Some-college 10 Married-civ-spouse Machine-op-inspct Husband        Black              Male   7688 0 40 United-States                >50K.
18 ?            103497 Some-college 10 Never-married      ?                 Own-child      White              Female 0    0 30 United-States               <=50K.
...                                                                                                                                                           ...
39 Private      215419 Bachelors    13 Divorced           Prof-specialty    Not-in-family  White              Female 0    0 36 United-States               <=50K.
64 ?            321403 HS-grad      9  Widowed            ?                 Other-relative Black              Male   0    0 40 United-States               <=50K.
38 Private      374983 Bachelors    13 Married-civ-spouse Prof-specialty    Husband        White              Male   0    0 50 United-States               <=50K.
44 Private      83891  Bachelors    13 Divorced           Adm-clerical      Own-child      Asian-Pac-Islander Male   5455 0 40 United-States               <=50K.
35 Self-emp-inc 182148 Bachelors    13 Married-civ-spouse Exec-managerial   Husband        White              Male   0    0 60 United-States                >50K.

[16281 rows x 1 columns]