In [10]:
import pandas as pd
a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data")
a

    18.0   8   307.0      130.0      3504.      12.0   70  1\t"chevrolet chevelle malibu"
0    15.0   8   350.0      165.0      3693.      11...
1    18.0   8   318.0      150.0      3436.      11...
2    16.0   8   304.0      150.0      3433.      12...
3    17.0   8   302.0      140.0      3449.      10...
4    15.0   8   429.0      198.0      4341.      10...
..                                                 ...
392  27.0   4   140.0      86.00      2790.      15...
393  44.0   4   97.00      52.00      2130.      24...
394  32.0   4   135.0      84.00      2295.      11...
395  28.0   4   120.0      79.00      2625.      18...
396  31.0   4   119.0      82.00      2720.      19...

[397 rows x 1 columns]

In [2]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 1 columns):
 #   Column                                                                                Non-Null Count  Dtype
---  ------                                                                                --------------  -----
 0   18.0   8   307.0      130.0      3504.      12.0   70  1	"chevrolet chevelle malibu"  397 non-null    object
dtypes: object(1)
memory usage: 3.2+ KB

In [ ]:
# when data space separated
# when data is comma separated
# a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None)
# a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None,delim_whitespace=True)
# a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None,delim_whitespace=True,na_values=["?"])
# a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None,delim_whitespace=True,na_values=["?"],names=["mpg","cylinders","displacement","horsepower","weight","acceleration","model year","origin","car name"])
# a.isnull().sum()



a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None,delim_whitespace=True)
a

NameError: name 'pd' is not defined

In [3]:
a.isnull().sum()

18.0   8   307.0      130.0      3504.      12.0   70  1\t"chevrolet chevelle malibu"    0
dtype: int64

In [13]:

a=pd.read_csv(r"C:\Users\subhadip sinha\Downloads\auto+mpg\auto-mpg.data",header=None,sep="\s+")
a

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]